blank_issues_enabled: false
contact_links:
  - name: Freature request
    url: https://forum.espocrm.com/forum/feature-requests
    about: "Use our forum for feature requests."
  - name: Forum
    url: https://forum.espocrm.com/
    about: "Use our forum for help requests and questions not related to product development. We don't provide support on GitHub."
